-- auto Generated on 2018-11-28 09:29:23 
-- DROP TABLE IF EXISTS `advertise`; 
CREATE TABLE advertise(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `advertise_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '广告ID',
    `title` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '主题',
    `text` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '文本内容',
    `url` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '点击链接',
    `image` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '图片链接',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'advertise';
