-- auto Generated on 2018-11-28 09:31:36 
-- DROP TABLE IF EXISTS `a_dynamic_image`; 
CREATE TABLE a_dynamic_image(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `dynamic_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '¶¯Ì¬ID',
    `image_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Í¼Æ¬ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'a_dynamic_image';
