-- auto Generated on 2018-11-28 09:31:31 
-- DROP TABLE IF EXISTS `a_group_permission`; 
CREATE TABLE a_group_permission(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `role_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT '½ÇÉ«ID',
    `permission_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'È¨ÏÞID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'a_group_permission';
