-- auto Generated on 2018-11-28 09:30:17 
-- DROP TABLE IF EXISTS `role`; 
CREATE TABLE role(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `role_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色ID',
    `role_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色名称',
    `role_desc` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色描述',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'role';
