-- auto Generated on 2018-11-28 10:35:21 
-- DROP TABLE IF EXISTS `user_group`; 
CREATE TABLE user_group(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `group_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '分组ID',
    `group_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '分组名称',
    `group_desc` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '分组描述',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user_group';
